### PR TITLE
New image CICFlowMeter

### PR DESCRIPTION
**Pull request by mielverkerken**

### CODE REVIEW

**Comment by Str-Gen** [comment]
Maybe check out [git submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules). As it stands it's a snapshot of the KUL codebase added directly here.

**Comment by mielverkerken** [comment]
> Maybe check out [git submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules). As it stands it's a snapshot of the KUL codebase added directly here.

I checked the submodules, would work for now. Still, the moment we want to change something to the image (extra configuration, data files, ...) we would first need to push it to their repository or work with a forked repository in between.

What do you prefer?

**Comment by Str-Gen** [comment]
Currently, as far as I see, the Dockerfile, the Makefile and the readme are new. They can exist one level above the cicflowmeter folder, which can be a submodule then.

**Comment by mielverkerken** [comment]
Created a new pull request with cicflowmeter added as a submodule: PR https://github.com/idlab-discover/image-infra-containercap/pull/4

**Pull request closed without merging**
